# Model arguments
model_name_or_path: /root/hybridGLAandNSA/ckpts_train_sft/checkpoint-96587
torch_dtype: bfloat16

# Data training arguments
# For definitions, see: src/h4/training/config.py
dataset_mixer:
  HuggingFaceH4/ultrafeedback_binarized: 1.0
  HuggingFaceH4/orca_dpo_pairs: 1.0
  JunxiongWang/llama3-ultrafeedback-armorm: 1.0
dataset_splits:
- train_prefs
- test_prefs
preprocessing_num_workers: 32

# DPOTrainer arguments
bf16: true
fp16: false
beta: 0.01
max_grad_norm: 1.0
do_eval: true
evaluation_strategy: steps
eval_steps: 2000
gradient_accumulation_steps: 1
gradient_checkpointing: false
gradient_checkpointing_kwargs:
  use_reentrant: False
learning_rate: 5.0e-7
log_level: info
logging_steps: 10
lr_scheduler_type: cosine
max_length: 3072
max_prompt_length: 2048
num_train_epochs: 1
optim: adamw_torch
output_dir: /root/hybridGLAandNSA/ckpts_train_dpo/
per_device_train_batch_size: 1
per_device_eval_batch_size: 2
push_to_hub: false
save_strategy: "steps"
save_steps: 2000
save_total_limit: 2
seed: 42
warmup_ratio: 0.1
truncation_mode: keep_start