# Model arguments
model_name_or_path: /root/hybridGlaAndNsa/ckpts_train_hybrid
decontaminate: true
torch_dtype: bfloat16

# Data training arguments
dataset_mixer:
  JunxiongWang/sftdataset: 1.0
dataset_splits:
- train
- test
preprocessing_num_workers: 2

# SFT trainer config
bf16: true
do_eval: true
evaluation_strategy: epoch
gradient_accumulation_steps: 1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
learning_rate: 2.5e-05
log_level: info
logging_steps: 10
logging_strategy: steps
lr_scheduler_type: cosine
max_seq_length: 4096
max_steps: -1
num_train_epochs: 1
output_dir: /root/hybridGlaAndNsa/ckpts_train_sft
overwrite_output_dir: true
per_device_eval_batch_size: 8
per_device_train_batch_size: 8
push_to_hub: false
remove_unused_columns: true

save_strategy: "steps"
save_steps: 4000
save_total_limit: 1
seed: 42
warmup_ratio: 0.01